import React from "react";

export default function Head() {
  return (
    <>
      <title>student-real-estate</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta
        name="description"
        content="Generated by
    student-real-estate"
      />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
