import Head from "next/head";
import { MantineProvider } from "@mantine/core";
import { ThemeProvider } from "next-themes";
import Header from "../components/Layout/Header";
import { Hero } from "../components/UI/Hero";
import { Section } from "../components/UI/Section";
import SearchSchools from "../components/UI/SearchSchools";
import Pagination from "../components/UI/Pagination";
import DirectMessage from "../components/UI/DirectMessage";
import Bg_image from "../components/UI/Bg_image";
import Footer from "../components/Layout/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MantineProvider theme={{ loader: "bars" }}>
        <ThemeProvider attribute="class">
          <Header />
          <Hero />
          <Section />
          <SearchSchools />
          <Pagination />
          <DirectMessage />
          <Bg_image />
          <Footer />
        </ThemeProvider>
      </MantineProvider>
    </div>
  );
}
